num1, num2 = input("enter two numbers ").split("and")
num1 = int(num1)
num2 = int(num2)
sum = num1 + num2
defference = num1 - num2
quotient = num1 / num2
remender = num1 % num2
product = num1*num2
print("{} + {} = {}".format(num1, num2, sum))
print("{} + {} = {}".format(num1, num2, defference))
print("{} + {} = {}".format(num1, num2, quotient))
print("{} + {} = {}".format(num1, num2, remender))
print("{} + {} = {}".format(num1, num2, product ))
